"""empty message

Revision ID: 1ea1a20f93cd
Revises: 385184e06269
Create Date: 2023-02-03 20:49:26.018760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ea1a20f93cd'
down_revision = '385184e06269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costumer', sa.Column('username', sa.String(length=80), nullable=False))
    op.add_column('costumer', sa.Column('address', sa.String(length=200), nullable=False))
    op.add_column('costumer', sa.Column('role', sa.String(length=80), nullable=False))
    op.add_column('costumer', sa.Column('phone', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('costumer', 'phone')
    op.drop_column('costumer', 'role')
    op.drop_column('costumer', 'address')
    op.drop_column('costumer', 'username')
    # ### end Alembic commands ###
