"""empty message

Revision ID: 28223afa4459
Revises: d49632f7ccd7
Create Date: 2023-02-03 23:07:54.524263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28223afa4459'
down_revision = 'd49632f7ccd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order__item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.Integer(), nullable=False),
    sa.Column('address', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order__item')
    # ### end Alembic commands ###
