"""empty message

Revision ID: 385184e06269
Revises: 50009c4dfcb9
Create Date: 2023-02-03 20:38:06.522433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385184e06269'
down_revision = '50009c4dfcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('costumer', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('costumer', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
