"""empty message

Revision ID: 466f7d2b218a
Revises: 79a402823989
Create Date: 2023-02-24 14:19:37.178407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466f7d2b218a'
down_revision = '79a402823989'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costumer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
