"""empty message

Revision ID: 74c6872bc891
Revises: 7c7b2cca1027
Create Date: 2023-02-03 21:51:18.715011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c6872bc891'
down_revision = '7c7b2cca1027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('costumer_id', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.create_foreign_key(None, 'product', 'costumer', ['costumer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'category_id')
    op.drop_column('product', 'costumer_id')
    # ### end Alembic commands ###
