"""empty message

Revision ID: 7c7b2cca1027
Revises: c6d0f9192393
Create Date: 2023-02-03 21:49:16.864136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7b2cca1027'
down_revision = 'c6d0f9192393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'product_id')
    # ### end Alembic commands ###
