"""empty message

Revision ID: 81c7ece92fa3
Revises: 239fb34edffc
Create Date: 2023-02-23 05:41:02.368650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81c7ece92fa3'
down_revision = '239fb34edffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('costumer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'costumer', ['costumer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('costumer_id')

    # ### end Alembic commands ###
