"""empty message

Revision ID: c6d0f9192393
Revises: f8b2483ca139
Create Date: 2023-02-03 21:47:15.221159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6d0f9192393'
down_revision = 'f8b2483ca139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('costumer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorites', 'costumer', ['costumer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'costumer_id')
    # ### end Alembic commands ###
