"""empty message

Revision ID: d49632f7ccd7
Revises: 1772fd1d3bd9
Create Date: 2023-02-03 22:41:36.538335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd49632f7ccd7'
down_revision = '1772fd1d3bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('costumer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'costumer', ['costumer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'costumer_id')
    # ### end Alembic commands ###
