"""empty message

Revision ID: f8b2483ca139
Revises: a75287d77650
Create Date: 2023-02-03 21:44:33.210412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b2483ca139'
down_revision = 'a75287d77650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_costumer_id_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_category_id_fkey', 'product', type_='foreignkey')
    op.drop_column('product', 'costumer_id')
    op.drop_column('product', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('costumer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('product_category_id_fkey', 'product', 'costumer', ['category_id'], ['id'])
    op.create_foreign_key('product_costumer_id_fkey', 'product', 'costumer', ['costumer_id'], ['id'])
    # ### end Alembic commands ###
